In [ ]:
import numpy as np
import util
import ctypes

In [ ]:
experiment_code = '2022-12-20-1600'
data_in_code = 'PLG2_tPA01_Q2.dat'
data_out_code = 'tPA425_PLG2_tPA01_into_and_along_Q2.dat';

In [ ]:
kiss_file = '../../lib/kiss.so'
kiss = ctypes.CDLL(kiss_file)

In [ ]:
urcw1 = kiss.urcw1_
urcw1.restype = ctypes.c_double

In [ ]:
state = [129281, 362436069, 123456789, -2137354075]

In [ ]:
state_type = ctypes.c_uint * 4
c_state = state_type(state[0], state[1], state[2], state[3])
kiss.set_kiss32_(c_state)
kiss.urcw1_()

In [ ]:
0.803214006701663

In [ ]:
state_type = ctypes.c_uint * 4

In [ ]:
get_kiss32 = kiss.get_kiss32_
#get_kiss32.restype = state_type

In [ ]:
c_state = state_type(0, 0, 0, 0)
for i in c_state:
    print(i)

In [ ]:
kiss.get_kiss32_(c_state)
for i in c_state:
    print(i)

In [ ]:
for i in c_state:
    print(i)

In [1]:
import lysis.util

In [2]:
kiss = lysis.util.KissRandomGenerator()
kiss.getstate()

(129281, 362436069, 123456789, 2740552755)

In [3]:
kiss.urcw1()

0.27521786659661873

In [4]:
kiss.random(10)

array([0.23341968, 0.59532045, 0.33051278, 0.53315702, 0.62713795,
       0.10086984, 0.70343299, 0.93950692, 0.94428388, 0.21012321])

In [8]:
a

array([0.34303259, 0.1090554 , 0.12355472, 0.34237657, 0.20872865,
       0.6944301 , 0.12358705, 0.39776014, 0.59589059, 0.09809339])

In [ ]:
kiss.urcw1()

In [ ]:
kiss.kiss32()

In [5]:
state = kiss.getstate()
state

(326169629, 2165843554, 4232839553, 547714037)

In [6]:
for i in range(4):
    print(kiss.kiss32())
    print(kiss.random(10))

1187407685
[0.68997542 0.40356682 0.77709113 0.8906236  0.52793443 0.61384521
 0.96461173 0.33523116 0.93725732 0.72401253]
452156582
[0.37011635 0.89190365 0.17900755 0.693691   0.62244893 0.32968103
 0.36977796 0.58899287 0.59853117 0.93144062]
2030912030
[0.66209783 0.1241452  0.29096173 0.06206618 0.81343398 0.70306094
 0.05151173 0.66953155 0.7236076  0.33672281]
2070212055
[0.28907965 0.23897837 0.24302226 0.29763629 0.88322848 0.09981336
 0.42352317 0.3041101  0.96393297 0.32396426]


In [7]:
for i in range(4):
    print(kiss.kiss32())
    print(kiss.random(10))

940552693
[0.8449937  0.50748539 0.29253247 0.96264399 0.9545566  0.3355127
 0.12707355 0.0480969  0.07818414 0.79974858]
2499226248
[0.01706247 0.64814462 0.17375444 0.64636391 0.3110065  0.69669605
 0.77682109 0.91401871 0.19079897 0.88025231]
1629471770
[0.24673167 0.34584072 0.00568217 0.43773395 0.09485262 0.28042533
 0.41089058 0.91464021 0.48141194 0.06513387]
616447383
[0.85073138 0.81567081 0.75687785 0.24325729 0.35509168 0.64204381
 0.18580485 0.9035831  0.94345685 0.78801176]


In [8]:
kiss.setstate(state)

In [9]:
for i in range(4):
    print(kiss.kiss32())
    print(kiss.random(10))

1187407685
[0.68997542 0.40356682 0.77709113 0.8906236  0.52793443 0.61384521
 0.96461173 0.33523116 0.93725732 0.72401253]
452156582
[0.37011635 0.89190365 0.17900755 0.693691   0.62244893 0.32968103
 0.36977796 0.58899287 0.59853117 0.93144062]
2030912030
[0.66209783 0.1241452  0.29096173 0.06206618 0.81343398 0.70306094
 0.05151173 0.66953155 0.7236076  0.33672281]
2070212055
[0.28907965 0.23897837 0.24302226 0.29763629 0.88322848 0.09981336
 0.42352317 0.3041101  0.96393297 0.32396426]


In [ ]:
kiss.set_state([129281, 362436069, 123456789, -2137354075])
kiss.urcw1()

In [ ]:
0.803214006701663

In [1]:
import lysis
import numpy as np

In [2]:
kiss = lysis.util.KissRandomGenerator()

In [3]:
kiss.random()

0.7132576634823578

In [5]:
a = kiss.integers(4, size=50)
a

array([3, 2, 1, 2, 0, 3, 3, 1, 3, 0, 1, 1, 2, 0, 2, 3, 1, 0, 0, 1, 1, 3,
       1, 1, 2, 2, 3, 0, 0, 0, 3, 2, 0, 0, 1, 1, 1, 3, 1, 0, 2, 0, 3, 3,
       3, 1, 1, 2, 1, 3])