In [1]:
import cProfile
import lysis
import math
import numpy as np

In [3]:
e = lysis.util.Experiment(r'../../data', experiment_code='2022-12-27-1100')

In [4]:
p = {'total_time': 1}
e.initialize_macro_param(p)
# e.read_file()

In [5]:
macro = lysis.MacroscaleRun(e)

In [6]:
macro.run()

100%|██████████| 2920/2920 [00:06<00:00, 473.87it/s]

Total binds: 10,992
Timesteps with changes to degrade time: 701
Total moves: 21,213,015
Total macro unbinds: 0
Total micro unbinds: 12


In [18]:
lysis.MacroscaleRun(e).run()

100%|█████████████████████████████████████████████████████████████████████████████| 2920/2920 [00:03<00:00, 809.72it/s]

Total binds: 11,054
Timesteps with changes to degrade time: 719
Total moves: 21,209,660
Total macro unbinds: 0
Total micro unbinds: 222


In [3]:
print(e)

experiment_code : 2022-12-27-1100
data_filenames  : unbinding_time : tsectPA.dat
                  lysis_time     : lysismat.dat
                  total_lyses    : lenlysisvect.dat
micro_params    : None
macro_params    : binding_rate       : 0.1
                  pore_size          : 0.00010135
                  diffusion_coeff    : 5e-07
                  binding_sites      : 427.0
                  forced_unbind      : 0.0852
                  average_bind_time  : 27.8
                  grid_node_distance : 1.0862
                  rows               : 93
                  cols               : 121
                  full_row           : 362
                  xz_row             : 241
                  total_edges        : 33545
                  total_fibers       : 23409
                  empty_rows         : 28
                  last_empty_edge    : 10135
                  total_molecules    : 43074
                  moving_probability : 0.2
                  microscale_runs    : 50

In [8]:
macro.location.nbytes

344592

In [9]:
macro.location.dtype

dtype('int64')

In [15]:
a = 499
b = 500
c = a*e.macro_params.time_step
d = b*e.macro_params.time_step

In [16]:
%timeit a < b

36.1 ns ± 0.269 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [17]:
%timeit c < d

33.1 ns ± 0.401 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [ ]:
lysis.from_fortran_edge_index(51, 4, 5)

In [ ]:
import numpy as np

In [ ]:
a = 3.5*np.ones((3, 4), dtype=np.double)
a[1][2]

In [ ]:
b = a[:2,:2]
b

In [ ]:
b[0,0] = 0
b

In [ ]:
a

In [ ]:
from enum import Enum, IntEnum, unique

In [ ]:
@unique
class Color(IntEnum):
    BLUE = 0
    RED = 1
    GREEN = 2
    
@unique
class Direction(Enum):
    UP = 1
    DOWN = -1

In [ ]:
Color.RED == Color.GREEN

In [ ]:
Color.RED == Direction.UP

In [ ]:
c = Color

In [ ]:
c.RED

In [ ]:
t = (Direction.UP, Direction.UP, Direction.DOWN)

In [ ]:
t[Color.BLUE]

In [ ]:
type(Direction.UP)

In [ ]:
isinstance(Direction.UP, Direction)

In [ ]:
import sys

In [ ]:
import lysis

In [10]:
a = np.ones((5, 10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
a[:3] = 3

In [12]:
a

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
A = np.empty((5, 10), dtype=object)
for i, j in np.ndindex(5, 10):
    A[i, j] = []

In [16]:
A[4, 3].append(4)

In [17]:
A

array([[list([]), list([]), list([]), list([]), list([]), list([]),
        list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([]), list([]), list([]),
        list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([]), list([]), list([]),
        list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([]), list([]), list([]),
        list([]), list([]), list([]), list([])],
       [list([]), list([]), list([]), list([4]), list([]), list([]),
        list([]), list([]), list([]), list([])]], dtype=object)

In [5]:
import numpy as 
rng = np.random.default_rng(seed=5748394)

In [4]:
a = cp.empty(10000)
%timeit rng.random(out=a)

55.2 µs ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
a = cp.empty(10000)
%timeit for i in cp.arange(a.size): a[i] = rng.random()

656 ms ± 42.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
float(rng.random())

0.8534137010574341

In [17]:
import lysis
import math
import numpy as np
import cupy as cp

from timeit import timeit

In [2]:
e = lysis.util.Experiment(r'../../data', experiment_code='2022-12-27-1100')
p = {'total_time': 1}
e.initialize_macro_param(p)
macro = lysis.MacroscaleRun(e)

In [3]:
macro.run()

100%|█████████████████████████████████████████████████████████████████████████████| 2920/2920 [00:08<00:00, 356.52it/s]

Total binds: 10445
Total moves: 21506701


In [4]:
m_fiber_status = macro.fiber_status[macro.location_i, macro.location_j]

In [15]:
macro.unbound_by_degradation[macro.bound & (m_fiber_status < 0.1)]

array([], dtype=float64)

In [14]:
print(f"{np.count_nonzero(macro.fiber_status > 2920*macro.exp.macro_params.time_step):,}")

23,409


In [13]:
print(f"{rng.random()*100:.2f}%")

77.90%


In [38]:
neighbors_i = np.empty(macro.neighbors_i.shape, dtype=np.short)
neighbors_i[:] = macro.neighbors_i
neighbors_j = np.empty(macro.neighbors_j.shape, dtype=np.short)
neighbors_j[:] = macro.neighbors_j

In [39]:
neighbors = np.empty(macro.neighbors_i.shape + (2,), dtype=np.short)
neighbors.shape

(93, 362, 8, 2)

In [40]:
for i, j, k in np.ndindex(macro.neighbors_i.shape):
    neighbors[i, j, k] = [macro.neighbors_i[i, j, k], macro.neighbors_j[i, j, k]]

In [31]:
temp = np.empty((30, 2), dtype=int)
tempx = np.empty(30, dtype=int)
tempy = np.empty(30, dtype=int)

In [32]:
%timeit temp = neighbors[aT[0], aT[1], 4]

3.41 µs ± 51.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [33]:
%timeit tempx = neighbors[aT[0], aT[1], 4, 0]; tempy = neighbors[aT[0], aT[1], 4, 1]

6.02 µs ± 60.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [34]:
%timeit temp = [macro.neighbors_i[aT[0], aT[1], 4], macro.neighbors_i[aT[0], aT[1], 4]]

6 µs ± 50.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [35]:
%timeit tempx = macro.neighbors_i[aT[0], aT[1], 4]; tempy = macro.neighbors_j[aT[0], aT[1], 4]

6.01 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [41]:
temp = np.empty((30, 2), dtype=np.short)
tempx = np.empty(30, dtype=np.short)
tempy = np.empty(30, dtype=np.short)

In [42]:
%timeit temp = neighbors[aT[0], aT[1], 4]

3.43 µs ± 37.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [43]:
%timeit tempx = neighbors[aT[0], aT[1], 4, 0]; tempy = neighbors[aT[0], aT[1], 4, 1]

5.99 µs ± 83.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [44]:
%timeit temp = [macro.neighbors_i[aT[0], aT[1], 4], macro.neighbors_i[aT[0], aT[1], 4]]

6.04 µs ± 84.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [45]:
%timeit tempx = macro.neighbors_i[aT[0], aT[1], 4]; tempy = macro.neighbors_j[aT[0], aT[1], 4]

5.96 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
rng = np.random.default_rng(seed=489489496)
crng = cp.random.default_rng(seed=489489496)

In [50]:
data = rng.random((30, 50))

In [131]:
location = np.append(rng.integers(10, size=(30, 1)), rng.integers(50, size=(30, 1)), axis=1)

In [49]:
locationx = rng.integers(10, size=30)
locationy = rng.integers(50, size=30)

In [52]:
location = np.concatenate((locationx, locationy)).reshape((2, -1))
locationT = location.T

In [47]:
%timeit locationx = rng.integers(10, size=30)

9.13 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
%timeit locationx = rng.integers(10, size=30, dtype=np.short)

9.2 µs ± 98.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
a = np.empty((30, 2), dtype=int)
a[:] = [[locationx[i], locationy[i]] for i in range(len(locationy))]
aT= a.T

In [ ]:
b = np.empty((30, 2), dtype=int)
b[:] = [[locationx[i], locationy[i]] for i in range(len(locationy))]
b

In [ ]:
c = np.empty((30, 2), dtype=int)
c

In [14]:
%timeit c[:] = [(a[i][0] + b[i][0], a[i][1] + b[i][1]) for i in np.arange(len(a))]

20.2 µs ± 687 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [22]:
%timeit for i in np.arange(len(a)): c[i] = (a[i][0] + b[i][0], a[i][1] + b[i][1])

20.1 µs ± 756 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
%timeit c[:] = [[a[i][0] + b[i][0], a[i][1] + b[i][1]] for i in np.arange(len(a))]

20.4 µs ± 409 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [35]:
%timeit for i in np.arange(len(a)): c[i] = [a[i][0] + b[i][0], a[i][1] + b[i][1]]

20.3 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [45]:
%timeit c[:] = [[a[i][0] + b[i][0], a[i][1] + b[i][1]] for i in np.arange(len(a))]

45.1 µs ± 872 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
%timeit for i in np.arange(len(a)): c[i] = [a[i][0] + b[i][0], a[i][1] + b[i][1]]

47.8 µs ± 712 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [29]:
%timeit c = a + b

530 ns ± 9.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
%timeit c = a

16.4 ns ± 0.21 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [61]:
a = rng.random()/rng.integers(100)
a

0.005930632152207066

In [63]:
a*10000 % 10

9.306321522070661

In [73]:
%timeit new_d = rng.random(data.shape, dtype=float)

165 µs ± 776 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [110]:
%timeit new_d = np.full(data.shape, False); new_d[data < 0.01] = rng.random(np.count_nonzero(data < 0.01)) > 0.75

37 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
data[(data < 0.01)]

In [115]:
np.count_nonzero(data < 0.01)

110

In [64]:
%timeit data[tuple(location.T)]

2.2 µs ± 9.33 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [128]:
locationT

NameError: name 'locationT' is not defined

In [78]:
data[locationx, locationy]

array([0.73752823, 0.57452464, 0.6823716 , 0.57814854, 0.42116801,
       0.35067002, 0.31266756, 0.51783093, 0.20255732, 0.56533216,
       0.57485138, 0.91181032, 0.73931556, 0.94478289, 0.42156745,
       0.4494924 , 0.42644033, 0.10955549, 0.94970583, 0.79183916,
       0.5095001 , 0.3913175 , 0.29846125, 0.41366644, 0.42644033,
       0.8902221 , 0.49076551, 0.21668166, 0.57452464, 0.94462407])

In [65]:
%timeit data[tuple(locationT)]

2.06 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [80]:
%timeit data[locationT[0], locationT[1]]

1.46 µs ± 11.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [79]:
%timeit data[locationx, locationy]

1.17 µs ± 7.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [82]:
%timeit data[locationx, locationy]

1.18 µs ± 14.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [41]:
period = 10
my_list = np.arange(period)
pointer = 8
count = 6
out = np.empty(count)

In [45]:
my_list[pointer:pointer+count]
out[:period-pointer] = my_list[pointer:]
out[period-pointer:] = my_list[:pointer+count-period]
pointer = pointer + count - period - 1
out, pointer

(array([8., 9., 0., 1., 2., 3.]), 3)

I want

out = [8, 9, 0, 1, 2, 3]
pointer = 3

In [157]:
a = np.array([(1,2),(1,3),(2,3),(1,2)]).T

In [163]:
np.unique(a, axis=1).shape

(2, 3)

In [154]:
a = np.array([locationx, locationy])

In [173]:
a

array([[1, 1, 2, 1],
       [2, 3, 3, 2]])

In [164]:
%timeit np.c_[locationx, locationy]

16.8 µs ± 44.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [165]:
%timeit np.dstack((locationx, locationy)).squeeze()

4.45 µs ± 56.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [166]:
%timeit np.vstack((locationx, locationy)).T

4.83 µs ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [167]:
%timeit np.concatenate((locationx, locationy)).reshape((-1, 2), order='F')

2.27 µs ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [38]:
np.concatenate((locationx, locationy)).reshape((2, -1))

array([[ 1,  9,  7,  5,  1,  9,  9,  7,  1,  2,  2,  8,  5,  7,  1,  7,
         7,  2,  6,  4,  5,  2,  0,  3,  7,  9,  3,  4,  4,  1],
       [ 9, 35,  4, 41,  3, 14, 43, 31,  3, 47, 18,  3, 15, 44, 22,  5,
        31, 47, 32,  0,  0,  3, 23, 45, 48, 46, 35, 24, 17, 19]],
      dtype=int64)

In [178]:
%timeit np.unique(np.concatenate((locationx, locationy)).reshape((-1, 2)), axis=0).shape[0]

54.2 µs ± 759 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [170]:
np.concatenate((locationx, locationy)).reshape((2, -1), order='C')

array([[ 0,  8,  8,  6,  4,  2,  7,  7,  3,  3,  3,  3,  1,  2,  3,  9,
         8,  1,  4,  4,  7,  2,  3,  0,  8,  6,  0,  7,  9,  8],
       [48, 37, 27, 17, 24, 47, 14, 40, 46,  6, 29, 15, 11, 33, 20, 36,
         2, 40,  2, 11, 10, 25, 43, 13, 35, 12, 26, 14, 13, 25]],
      dtype=int64)

In [182]:
a = np.empty(5, dtype=int)
b = rng.random(5)*10
a[:] = b
a, b

(array([8, 8, 2, 1, 8]),
 array([8.45630955, 8.6679034 , 2.2179064 , 1.40474837, 8.05285945]))

In [2]:
import cupy as cp

In [5]:
data

array([[0.99837226, 0.23504539, 0.5805279 , ..., 0.04231225, 0.86683309,
        0.76809978],
       [0.15520181, 0.40666112, 0.65112925, ..., 0.78392226, 0.07917176,
        0.83056718],
       [0.92990172, 0.13181619, 0.63987201, ..., 0.78127569, 0.04968871,
        0.25467855],
       ...,
       [0.82053894, 0.72198588, 0.21543927, ..., 0.48202854, 0.2880998 ,
        0.68291485],
       [0.44019663, 0.80035603, 0.99645919, ..., 0.11915003, 0.26551479,
        0.57375377],
       [0.90528816, 0.2954731 , 0.77608824, ..., 0.87461948, 0.11690058,
        0.35273913]])

In [8]:
int(cp.count_nonzero(data > 0.7))

459

In [3]:
import lysis

In [5]:
neighbors = lysis.EdgeGrid.generate_neighborhood_structure(e)

In [6]:
neighbors

array([[    1,     1,   363, ...,   364,     2,   364],
       [    0,     0,     0, ...,     2,     2,     2],
       [    0,     3,     0, ...,     1,     4,     4],
       ...,
       [33299, 33302, 33299, ..., 33662, 33665, 33665],
       [65535, 65535, 65535, ..., 65535, 65535, 65535],
       [33302, 33302, 33302, ..., 33663, 33663, 33663]], dtype=uint16)

In [3]:
%timeit rand = rng.random(100000)

333 µs ± 3.07 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
%timeit rand = crng.random(1281*10)

15.5 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [29]:
for i in np.arange(120, 190):
    t = timeit(stmt="for j in np.arange(10000000//(i * 1000)): " +
               "temp[1000*i*j:(1000*i)*(j+1)] = crng.random(1000*i)",
               setup="temp = cp.full(10000000, 0.0, dtype=float)",
               number=1000, globals=globals())
    print(f"{10000000//(i * 1000)}x{1000*i}: {t:.3}")

83x120000: 9.39
82x121000: 9.11
81x122000: 9.07
81x123000: 9.14
80x124000: 9.11
80x125000: 9.16
79x126000: 9.12
78x127000: 9.08
78x128000: 9.15
77x129000: 9.09
76x130000: 9.05
76x131000: 9.11
75x132000: 9.27
75x133000: 9.34
74x134000: 9.28
74x135000: 9.33
73x136000: 9.26
72x137000: 9.22
72x138000: 9.26
71x139000: 9.21
71x140000: 9.25
70x141000: 9.2
70x142000: 9.24
69x143000: 9.18
69x144000: 9.23
68x145000: 9.16
68x146000: 9.21
68x147000: 9.27
67x148000: 9.19
67x149000: 9.26
66x150000: 9.19
66x151000: 9.25
65x152000: 9.18
65x153000: 9.21
64x154000: 9.12
64x155000: 9.16
64x156000: 9.21
63x157000: 9.14
63x158000: 9.2
62x159000: 9.08
62x160000: 9.15
62x161000: 9.22
61x162000: 9.1
61x163000: 9.15
60x164000: 9.07
60x165000: 9.13
60x166000: 9.15
59x167000: 9.08
59x168000: 9.11
59x169000: 9.18
58x170000: 9.07
58x171000: 9.13
58x172000: 9.27
57x173000: 9.02
57x174000: 9.11
57x175000: 9.16
56x176000: 9.06
56x177000: 9.11
56x178000: 9.12
55x179000: 8.98
55x180000: 9.21
55x181000: 9.12
54x182000: 