In [1]:
import util.parameters
from datetime import datetime
import json

In [2]:
e = util.parameters.Experiment()
e.initialize_macro_param("Diffuse into and along")
#now = datetime.now()
#str(now.year) + '_'

In [3]:
e.to_dict()

{'experiment_code': '2022_12_24_1624',
 'macro_params': {'macro_version': 'Diffuse into and along',
  'rows': 93,
  'cols': 121,
  'first_fiber_row': 28,
  'moving_probability': 0.2,
  'pore_size': 0.00010135,
  'diffusion_coeff': 5e-07,
  'total_time': 600,
  'full_row': 278,
  'xz_row': 185,
  'total_fibers': 33545,
  'last_ghost_fiber': 10135,
  'time_step': 0.0003423940833333333,
  'total_time_steps': 1752366.729467921,
  'binding_rate': 0.01,
  'binding_sites': 427.0,
  'grid_symmetry_distance': 1.0862,
  'total_molecules': 43074,
  'total_trials': 10,
  'seed': 912309035,
  'state': [129281, 362436069, 123456789, 912309035],
  'unbinding_time_filename': 'tsectPA',
  'lysis_time_filename': 'lysismat',
  'total_lyses_filename': 'lenlysisvect',
  'lysis_blocks': 100,
  'unbinds_per_block': 500,
  'max_lyses_per_block': 283}}

In [4]:
with open('params.json', 'w') as file:
    json.dump(e.to_dict(), file)

In [10]:
with open('params.json', 'r') as file:
    a = json.load(file)

In [5]:
type(e.macro_params)

util.parameters.MacroParameters

In [2]:
p=util.parameters.Parameters()

In [3]:
p.rows

0

In [4]:
p.rows = 15

In [5]:
p.rows

15


Initial settings
filename         : 'settings1.txt'
last_time_stored : '2022-12-28T14:48:42.694793'
targetServer     : 'whitehouse1'
userId           : 'obama_barak'

Settings after modification
filename         : 'settings1.txt'
last_time_stored : '2022-12-28T14:48:42.697854'
targetServer     : 'whitehouse1'
userId           : 'biden_joe'

Settings after deletion of userId
filename         : 'settings1.txt'
last_time_stored : '2022-12-28T14:48:42.697854'
targetServer     : 'whitehouse1'


In [1]:
import numpy as np

In [4]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = a[:2,:2]
b

array([[1, 2],
       [4, 5]])

In [7]:
b[0,0] = 0
b

array([[0, 2],
       [4, 5]])

In [8]:
a

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
from enum import Enum, unique

In [12]:
@unique
class Color(Enum):
    RED = 1
    GREEN = 2
    
@unique
class Direction(Enum):
    UP = 1
    DOWN = -1

In [13]:
Color.RED == Color.GREEN

False

In [14]:
Color.RED == Direction.UP

False

In [16]:
c = Color

In [17]:
c.RED

<Color.RED: 1>